[phases.setup]
nixPkgs = ["caddy", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "node dist-server/server.js & caddy run --config /app/Caddyfile --adapter caddyfile"

[assets."./Caddyfile"]
target = "/app/Caddyfile"
